import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components/ui/navbar';
import Banner from './acercademi/banner';
import Footer from '@/components/ui/footer';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className=''>
			<body
				className={cn(
					'flex flex-col bg-background font-sans antialiased h-screen',
					fontSans.variable,
				)}
			>
				<main className='flex flex-col flex-grow '>
					<Navbar />
					<div className='bg-slate-200 pt-3 pb-3'>
						<Banner />
						<br />
					</div>

					<div className='flex-grow sm:mx-24 mx-3 mt-5'>
						{children}
					</div>

					<Footer />
				</main>
			</body>
		</html>
	);
}
